image: trion/ng-cli

variables:
  BASE_URL: "flexy-demy"
  PROJECT_NAME: "flexy-demy-ui"
  BUILD_FOLDER: "/app/dist/flexy-demy-ui/browser"
  HOST_DEPLOY_PATH: "/c/docker/nginx/html"

stages:
  - build_development
  - deploy_development

build_development:
  stage: build_development
  only:
    - elsoft
  script:
    - docker build --build-arg NODE_ENV=development -t $PROJECT_NAME:development .
    - docker create --name temp-$PROJECT_NAME $PROJECT_NAME:development
    - mkdir -p $HOST_DEPLOY_PATH
    - docker cp temp-$PROJECT_NAME:$BUILD_FOLDER/. $HOST_DEPLOY_PATH/
    - docker rm temp-$PROJECT_NAME

deploy_development:
  stage: deploy_development
  only:
    - elsoft
  script:
    - docker stop $PROJECT_NAME-dev || true
    - docker rm $PROJECT_NAME-dev || true
    - docker run -d -p 4200:80 \
      --name $PROJECT_NAME-dev \
      -v $HOST_DEPLOY_PATH:/usr/share/nginx/html \
      nginx:alpine

build_production:
  stage: build_production
  only:
    - main
  script:
    - npm cache clean --force
    - npm install --force --legacy-peer-deps
    #    - echo "${BASE_URL}"
    #    - ng build --configuration=production --base-href='./'
    - docker build --build-arg NODE_ENV=production --build-arg NODE_PORT=80 -t flexy-demy-ui:production .
    - |
      $CONTAINER_NAMES = docker ps --format '{{.Names}}' | ForEach-Object { $_.Trim() }
      if ($CONTAINER_NAMES -like "*flexy-demy-ui-prod*") {
        docker stop flexy-demy-ui-prod
        docker rm flexy-demy-ui-prod
      }
    - docker run -d -p 80:80 --name flexy-demy-ui-prod flexy-demy-ui:production
#deploy_production:
#  stage: deploy_production
#  only:
#    - main
#  script:
#    - rm -rf "C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/${BASE_URL}"
#    - xcopy /s /y "${BASE_URL}" "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\${BASE_URL}"
#    - rm -r "C:/Users/Administrator.ORNATE-TECH/AppData/Local/Jenkins/.jenkins/caches/*"
#
#deploy_development:
#  stage: deploy_development
#  only:
#    - dev
#  script:
#    - rm -rf "C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/${BASE_URL}dev"
#    - xcopy /s /y "${BASE_URL}dev" "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\${BASE_URL}dev"
#    - rm -r "C:/Users/Administrator.ORNATE-TECH/AppData/Local/Jenkins/.jenkins/caches/*"
