image: trion/ng-cli

variables:
  BASE_URL: "flexy-demy"
  PROJECT_NAME: "flexy-demy-ui"
  HOST_DEPLOY_PATH: "/c/docker/nginx/html"

stages:
  - install
  - build_development
  - build_production
  - deploy_production
  - deploy_development


install:
  stage: install
  script:
    - npm install --force --legacy-peer-deps


build_development:
  stage: build_development
  only:
    - elsoft
  script:

    - docker build --build-arg NODE_ENV=development -t ${PROJECT_NAME}-builder .
    - docker rm -f temp-${PROJECT_NAME} || true
    - docker create --name temp-${PROJECT_NAME} ${PROJECT_NAME}-builder
    - powershell -Command "Remove-Item -Path '${HOST_DEPLOY_PATH}\*' -Recurse -Force"
    - docker cp temp-${PROJECT_NAME}:/app/dist/browser/. ${HOST_DEPLOY_PATH}
    - docker rm temp-${PROJECT_NAME}
    - docker restart flexy-central-nginx

build_production:
  stage: build_production
  only:
    - main
  script:
    - npm cache clean --force
    - npm install --force --legacy-peer-deps
    #    - echo "${BASE_URL}"
    #    - ng build --configuration=production --base-href='./'
    - docker build --build-arg NODE_ENV=production --build-arg NODE_PORT=80 -t flexy-demy-ui:production .
    - |
      $CONTAINER_NAMES = docker ps --format '{{.Names}}' | ForEach-Object { $_.Trim() }
      if ($CONTAINER_NAMES -like "*flexy-demy-ui-prod*") {
        docker stop flexy-demy-ui-prod
        docker rm flexy-demy-ui-prod
      }
    - docker run -d -p 80:80 --name flexy-demy-ui-prod flexy-demy-ui:production
#deploy_production:
#  stage: deploy_production
#  only:
#    - main
#  script:
#    - rm -rf "C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/${BASE_URL}"
#    - xcopy /s /y "${BASE_URL}" "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\${BASE_URL}"
#    - rm -r "C:/Users/Administrator.ORNATE-TECH/AppData/Local/Jenkins/.jenkins/caches/*"
#
#deploy_development:
#  stage: deploy_development
#  only:
#    - dev
#  script:
#    - rm -rf "C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/${BASE_URL}dev"
#    - xcopy /s /y "${BASE_URL}dev" "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\${BASE_URL}dev"
#    - rm -r "C:/Users/Administrator.ORNATE-TECH/AppData/Local/Jenkins/.jenkins/caches/*"
